# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjlBvWEzsCllZlJzTdvLtxYsPCUrLsPl
"""

print('hola mundo')